unbanlist: ['Hedgeko','Florecko','Sentecko','Scorchog','Bombardillo','Kabangolin','Fisker','Catfisk','Nekimono','Elfae',
'Elfae-Cherry','Elfae-Caramel','Elfae-Lemon','Elfae-Mint','Elfae-Blueberry','Elfae-Grape','Elfae-Cotton Candy','Elfae-Licorice','Fanshee','Reveram',
'Sporasol','Bumbashoo','Umbrelala','Dimlit','Glimmwit','Nummsglow','Sentrode','Shokputz','Reknology','Batorch',
'Vampyro','Sliggibak','Imisnake','Resemboa','Minatlas','Thornatlas','Squift','Seanobi','Ambiggle','Ambiggle-Fever',
'Ambiggle-Chill','Ambiggle-Stun','Ambiggle-Nausea','Ambiggle-Slumber','Koikoi-Pawn','Koikoi-King','Koikoi-Rook','Koikoi-Queen','Koikoi-Bishop','Koikoi-Knight',
'Gomokoi-Pawn','Gomokoi-King','Gomokoi-Rook','Gomokoi-Queen','Gomokoi-Bishop','Gomokoi-Knight','Castallop','Cymbarine','Gnawful','Cragodile',
'Slicky','Goomarsh','Polymoor','Fooldya','Dupedual','Brughoul','Vanghost','Picassoul','Jokai','Hanbone',
'Skullvis','Frounder','Sunfoon','Solasola','Snowki','Snowkoro','Friwi','Decorane','Hopshok','Pounshok',
'Myoesee','Quilapila','Magnumoth','Maskito','Bolichi','Minelk','Elkler','Plattle','Ornithor','Fangon',
'Flanket','Orienchant','Tikare','Nicepak','Nursaleve','Nooby','Proteen','Dramatama','Veyel','Smieel',
'Neesoks','Skinky','Admirror','Majestice','Camery','Camellac','Moustash','Hampstor','Archovy','Marksmelt',
'Bulsye','Murezhu','Signapse','Poyolky','Hawkadoo','Valoroost','Orkid','Orchette','Fyrena','Magmutt',
'Smook','Sliquish','Sluggoth','Sluggoon','Quiklaw','Outklaw','Snooball','Snooman','Snoofort','Slowth',
'Slothargic','Atomix','Daggon','Dynasord','Rexcaliber-Sheathed','Rexcaliber-Unsheathed','Sparfish','Dryzard','Dehydrake','Kappunk',
'Voodood','Hagayaga','Flanbon','Terramisu','Elemur','Gleemur','Skreemur','Budifoal','Bloomare','Bronxy',
'Behemox','Saunhaug','Crestendo','Melodyna','Corraptor','Nefaraptor','Taigla','Pumafrost','Fereeze','Pandit',
'Bearglar','Iggnit','Kerofin','Inferlotl','Ravenge','Pompoke','Ogroak','Humbuzz','Beezooka','Beemuze',
'Rogguard','Zentinal-Earth','Zentinal-Sky','Chantaray','Enchantaray','Yokkameo','Pogguest','Hyperiogg','Jinghoul','Azuryx',
'Vermilyx','Pallyx','Ouroska','Boroska','Shivatna','Ebonyx','Kamizzama','Seraphine','Ophamine','Tengyuma',
'Navaroc','Hajimi-New Moon','Hajimi-Full Moon','Hopponit','Buddhop','Meditoad','Lavur','Mohaut','Pompadire','Pintcha',
'Crabalier','Skaladin','Calforie','Bultter','Taurgarine','Terooboo','Zellha','Soullha','Snowble','Cupengy',
'Auroyal','Monana','Kabukey','Bat1','Bat2','Bat3','Snake1','Snake2','Snake3','Croc1',
'Croc2','Croc3'],